export const projects = [
  {
    id: 1,
    name: "crosmos",
    role: "co-founder · crosmos-labs",
    description: "context infrastructure for teams and agents",
    href: "/projects#crosmos",
    tech: ["Python", "TypeScript", "MCP", "Knowledge Graphs", "AI Memory"],
    link: "https://crosmos.dev",
  },
  {
    id: 2,
    name: "ironic",
    role: "co-founder · crosmos-labs",
    description:
      "open-source SDK and MCP server generation from your OpenAPI spec, fully compatible with stainless.yml",
    href: "/projects#ironic",
    tech: ["TypeScript", "OpenAPI", "MCP", "SDKs"],
    link: "https://github.com/crosmos-labs/ironic",
  },
  {
    id: 3,
    name: "hush",
    role: "creator and maintainer",
    description: "fast, lightweight and encrypted secrets manager CLI in Rust",
    href: "/projects#hush",
    tech: ["Rust", "Argon2", "Clap", "ChaCha20poly1305"],
    link: "https://github.com/Ethics03/hush",
  },
  {
    id: 4,
    name: "dex",
    role: "creator",
    description:
      "a visual agentic workflow builder with drag-and-drop nodes, has gmail and gemini integration.",
    href: "/projects#hush",
    tech: ["ExpressJS", "BullMQ", "Redis", "NextJS", "Shadcn", "Reactflow"],
    link: "https://github.com/Ethics03/dex-core",
  },

  {
    id: 5,
    name: "dots",
    role: "creator",
    description: "dotfile manager cli in go with git sync",
    href: "/projects#dots",
    tech: ["Go", "cobra-cli", "git"],
    link: "https://github.com/Ethics03/dots",
  },
  {
    id: 6,
    name: "uriel",
    role: "Creator",
    description: "api testing with ai security suggestions using Ollama3",
    href: "/projects#uriel",
    tech: ["Go", "cobra-cli", "ollama3", "net/http"],
    link: "https://github.com/Ethics03/uriel",
  },
  {
    id: 7,
    name: "minpin",
    role: "Creator",
    description: "a url shortener in golang and postgresql",
    tech: ["Golang", "PostgreSQL", "net/http"],
    link: "https://github.com/Ethics03/minpin",
  },
];
